name: Test & Deploy

on:
  push:
    branches:
      - deploy

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Clone Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Test Utils
        run: npm test utils

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: testperson
          postgresql password: password
      
      - name: Test App Endpoints
        run:  PGADATABASE=test_db PGUSER=testperson PGAPASSWORD=password npm test app

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout & Clone Repo
        uses: actions/checkout@v

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}